---
- hosts: azurevms
  gather_facts: no
  tasks:
    - name: Install IIS features
      win_feature:
        name:
          - web-Server
          - web-common-Http
        include_management_tools: yes
        state: present

    - name: Enable IIS remote management
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Microsoft\WebManagement\Server
        name: EnableRemoteManagement
        data: 1
        type: dword
    - name: Install WebDeploy
      win_package:
          path: https://download.microsoft.com/download/0/1/D/b462d350-1ac8-4373-a8c5-deadc8357530/WebDeploy_amd64_en-US.msi
          product_id: ''
          arguements: ADDLOCAL=ALL
          state: present
    - name: Start and set management service to auto 
      win_service:
       name: WMSvc
       start_mode: auto 
       state: started
    - name: install net core iis hosting module with no frameworks
      win_chocolatey:
        name: "dotnetcore-windowshosting"
        version: latest
        install_args: "OPT_NO_SHARED_CONFIG_CHECK=1"
      notify: restart IIS 
    - name: Create logging directory
      win_file: 
        path: c:\logs
        state: directory
  handlers:
    - name: restart IIS
      win_shell: '& {iisreset}'
